#:kivy 1.0
<ToolBox>:
	Label:
		text: 'My label before button press'
	canvas:		
		label_wid: my_custom_label
        Rectangle:
            pos: self.center_x - 5, 0
            size: 10, self.height	
	FloatLayout:
        padding: 20
		StackLayout:
			orientation: 'lr-tb'
			Button:
				text: 'My controller info is : ' + root.info
				on_press: root.do_action()
			Label:
				id: my_custom_label
				text: 'My label before button press'     	
